"""
COM object type stubs for the outlook-desktop-mcp package.

pywin32 exposes Outlook's COM API through runtime dispatch, which means
the actual Python types are dynamic (no static type info). To get useful
type-checking and IDE help without depending on the unmaintained
`win32com.client` stubs, we declare a small set of Protocol classes that
describe only the methods/properties we actually call.

These are *structural* types: any COM object with the right attributes will
satisfy them, even though it isn't actually a subclass.

Convention:
    - `Outlook`      — the top-level COM Application object (CreateItem, Session)
    - `Namespace`    — MAPI namespace (Stores, GetItemFromID, DefaultStore)
    - `Store`        — message store (GetDefaultFolder, GetRootFolder, DisplayName)
    - `Folder`       — calendar/mail/task folder (Folders, Items, Name)
    - `Account`      — Outlook account (DeliveryStore)
    - `MailItem`     — Outlook mail item (To, CC, BCC, Subject, Body, Send, ...)
    - `Appointment`  — calendar item (Start, End, Subject, Move, Save, Recipients, ...)
    - `TaskItem`     — task item (Subject, Body, DueDate, Importance, ...)
    - `GenericItem`  — any MAPI item (Class, EntryID, Subject, Body, Delete, ...)
    - `Recipient`    — mail/appointment recipient (Type)

For one-off vars (e.g. `acc` for an account, `appt_obj` for a re-fetched appt)
we use the generic pseudo-type alias `AnyCOM` (= Any) so a quick local rename
isn't blocked by strict type checking.
"""

from __future__ import annotations

from typing import Any, Protocol, Self, runtime_checkable

# Convenience alias for COM objects we don't have a Protocol for.
# Used sparingly — prefer declaring a Protocol when an attribute set is reused.
type AnyCOM = Any


@runtime_checkable
class Folder(Protocol):
    """A calendar/mail/task folder. Used as return type of folder resolution."""

    @property
    def Name(self) -> str: ...
    @property
    def Folders(self) -> Folders:  # ty: ignore[invalid-type-form]  -- see block comment on Stores
        ...
    @property
    def Items(self) -> Any: ...
    @property
    def UnReadItemCount(self) -> int: ...
    def Item(self, index: Any) -> GenericItem: ...


@runtime_checkable
class Folders(Protocol):
    """A collection of Folder objects (Parent.Folders)."""

    @property
    def Count(self) -> int: ...
    def Item(self, index: Any) -> Folder: ...


@runtime_checkable
class Store(Protocol):
    """An Outlook message store (account)."""

    @property
    def StoreID(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def GetRules(self) -> Any: ...
    @property
    def PropertyAccessor(self) -> Any: ...
    def GetDefaultFolder(self, folder_type: int) -> Folder: ...
    def GetRootFolder(self) -> Folder: ...


@runtime_checkable
class Stores(Protocol):
    """A collection of Store objects (Namespace.Stores)."""

    @property
    def Count(self) -> int: ...
    def Item(self, index: Any) -> Store: ...


@runtime_checkable
class Account(Protocol):
    """An Outlook account entry (used for sending-as)."""

    @property
    def DeliveryStore(self) -> Store: ...


@runtime_checkable
class Accounts(Protocol):
    @property
    def Count(self) -> int: ...
    def Item(self, index: Any) -> Account: ...


@runtime_checkable
class Recipients(Protocol):
    """A collection of Recipient objects (appointment/mail Recipients)."""

    def Add(self, address: str) -> Recipient: ...
    def ResolveAll(self) -> None: ...


@runtime_checkable
class Recipient(Protocol):
    @property
    def Type(self) -> int: ...


@runtime_checkable
class GenericItem(Protocol):
    """A MAPI item — base for mail/appointment/task. Used for ID-based lookup.

    Includes the union of attributes that exist on *any* Outlook item class
    (mail, appointment, task). For type-narrowed access (e.g. ``item.Start``
    for an appointment), declare the local as a specific Protocol
    (``Appointment``, ``MailItem``, ``TaskItem``).
    """

    @property
    def Class(self) -> int: ...
    @property
    def EntryID(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Subject(self) -> str: ...
    @property
    def Body(self) -> str: ...
    @Body.setter
    def Body(self, value: str) -> None: ...
    @property
    def HTMLBody(self) -> str: ...
    @HTMLBody.setter
    def HTMLBody(self, value: str) -> None: ...
    @property
    def Categories(self) -> str: ...
    @Categories.setter
    def Categories(self, value: str) -> None: ...
    @property
    def UnRead(self) -> bool: ...
    @UnRead.setter
    def UnRead(self, value: bool) -> None: ...
    @property
    def Attachments(self) -> Any: ...
    @property
    def MeetingStatus(self) -> int: ...
    @MeetingStatus.setter
    def MeetingStatus(self, value: int) -> None: ...
    def Delete(self) -> None: ...
    def Move(self, folder: Folder) -> Self: ...
    def Save(self) -> None: ...
    def Send(self) -> None: ...
    def Reply(self, *args: Any) -> Any: ...
    def ReplyAll(self) -> Any: ...
    def Respond(self, response: Any, *args: Any) -> Any: ...


@runtime_checkable
class MailItem(Protocol):
    """An Outlook mail item (CreateItem(0))."""

    @property
    def Class(self) -> int: ...
    @property
    def Subject(self) -> str: ...
    @Subject.setter
    def Subject(self, value: str) -> None: ...
    @property
    def Body(self) -> str: ...
    @Body.setter
    def Body(self, value: str) -> None: ...
    @property
    def HTMLBody(self) -> str: ...
    @HTMLBody.setter
    def HTMLBody(self, value: str) -> None: ...
    @property
    def To(self) -> str: ...
    @To.setter
    def To(self, value: str) -> None: ...
    @property
    def CC(self) -> str: ...
    @CC.setter
    def CC(self, value: str) -> None: ...
    @property
    def BCC(self) -> str: ...
    @BCC.setter
    def BCC(self, value: str) -> None: ...
    @property
    def EntryID(self) -> str: ...
    @property
    def Attachments(self) -> Any: ...
    def Send(self) -> None: ...
    def Reply(self, *args: Any) -> Any: ...
    def ReplyAll(self) -> Any: ...
    def Move(self, folder: Folder) -> Self: ...
    def Save(self) -> None: ...
    def Delete(self) -> None: ...
    # Low-level COM escape hatch (used for setting the sending account via _SendUsingAccount)
    @property
    def _oleobj_(self) -> Any: ...


@runtime_checkable
class Appointment(Protocol):
    """An Outlook calendar appointment (CreateItem(1))."""

    @property
    def Class(self) -> int: ...
    @property
    def Subject(self) -> str: ...
    @Subject.setter
    def Subject(self, value: str) -> None: ...
    @property
    def Start(self) -> Any: ...
    @Start.setter
    def Start(self, value: Any) -> None: ...
    @property
    def End(self) -> Any: ...
    @End.setter
    def End(self, value: Any) -> None: ...
    @property
    def Location(self) -> str: ...
    @Location.setter
    def Location(self, value: str) -> None: ...
    @property
    def Body(self) -> str: ...
    @Body.setter
    def Body(self, value: str) -> None: ...
    @property
    def EntryID(self) -> str: ...
    @property
    def AllDayEvent(self) -> bool: ...
    @AllDayEvent.setter
    def AllDayEvent(self, value: bool) -> None: ...
    @property
    def ReminderSet(self) -> bool: ...
    @ReminderSet.setter
    def ReminderSet(self, value: bool) -> None: ...
    @property
    def ReminderMinutesBeforeStart(self) -> int: ...
    @ReminderMinutesBeforeStart.setter
    def ReminderMinutesBeforeStart(self, value: int) -> None: ...
    @property
    def MeetingStatus(self) -> int: ...
    @MeetingStatus.setter
    def MeetingStatus(self, value: int) -> None: ...
    @property
    def Recipients(self) -> Recipients:  # ty: ignore[invalid-type-form]  -- Protocol self-ref; see note on Stores
        ...
    def Send(self) -> None: ...
    def Move(self, folder: Folder) -> Self: ...
    def Save(self) -> None: ...
    def Delete(self) -> None: ...
    def Respond(self, response: Any, *args: Any) -> Any: ...
    # Low-level COM escape hatch (used for setting the sending account via _SendUsingAccount)
    @property
    def _oleobj_(self) -> Any: ...


@runtime_checkable
class TaskItem(Protocol):
    """An Outlook task item (CreateItem(5))."""

    @property
    def Class(self) -> int: ...
    @property
    def Subject(self) -> str: ...
    @Subject.setter
    def Subject(self, value: str) -> None: ...
    @property
    def Body(self) -> str: ...
    @Body.setter
    def Body(self, value: str) -> None: ...
    @property
    def EntryID(self) -> str: ...
    @property
    def DueDate(self) -> Any: ...
    @DueDate.setter
    def DueDate(self, value: Any) -> None: ...
    @property
    def Importance(self) -> int: ...
    @Importance.setter
    def Importance(self, value: int) -> None: ...
    @property
    def ReminderSet(self) -> bool: ...
    @ReminderSet.setter
    def ReminderSet(self, value: bool) -> None: ...
    @property
    def ReminderMinutesBeforeStart(self) -> int: ...
    @ReminderMinutesBeforeStart.setter
    def ReminderMinutesBeforeStart(self, value: int) -> None: ...
    @property
    def Status(self) -> int: ...
    @Status.setter
    def Status(self, value: int) -> None: ...
    @property
    def PercentComplete(self) -> int: ...
    @PercentComplete.setter
    def PercentComplete(self, value: int) -> None: ...
    @property
    def UnRead(self) -> bool: ...
    def Move(self, folder: Folder) -> Self: ...
    def Save(self) -> None: ...
    def Delete(self) -> None: ...


@runtime_checkable
class Namespace(Protocol):
    """The MAPI namespace (outlook.Session)."""

    @property
    def Stores(self) -> Stores:  # ty: ignore[invalid-type-form]  -- see note below
        ...
    @property
    def DefaultStore(self) -> Store: ...
    @property
    def Accounts(self) -> Accounts:  # ty: ignore[invalid-type-form]  -- same self-ref limitation as Stores/Recipients/Folders
        ...
    @property
    def Categories(self) -> Any: ...
    def GetItemFromID(self, entry_id: str, store_id: str | None = ...) -> GenericItem: ...


# NOTE: ty flags `def Stores(self) -> "Stores"`, `def Recipients(self) -> "Recipients"`,
# and `def Folders(self) -> "Folders"` (in `Folder.Folders`) as
# `invalid-type-form` (Variable of type `property` is not allowed in a return type).
# This is a known ty limitation with Protocol self-references: when a property name
# matches a class name in the class body, ty's name resolver picks up the property
# descriptor instead of the class. The Python runtime handles forward-reference
# strings correctly (see test_blank_subject_guard.py which imports _types successfully
# and satisfies all Protocols with mock objects). We accept these ty warnings
# here because the alternative (renaming the Protocols, or using `Self` which
# loses the collection-typed methods like .Add()/.ResolveAll() on Recipients and
# .Item()/.Count() on Stores/Folders) would degrade type safety elsewhere.


@runtime_checkable
class Outlook(Protocol):
    """The top-level Outlook application (COM Application object)."""

    @property
    def Session(self) -> Namespace: ...
    def CreateItem(self, item_type: int) -> Any: ...
    # Low-level COM invocation (used for setting the sending account on meetings)
    @property
    def _oleobj_(self) -> Any: ...
